import { Footer } from "@/app/components/landpage/Footer";
import Navbar from "@/app/components/landpage/Navbar";
import { i18n, Locale } from "@/i18n";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description:
    "Generated by create next app",
};

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({
    lang: locale,
  }));
}

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { lang: Locale };
}) {
  return (
    <html lang={params.lang}>
      <body className={inter.className}>
        <Navbar params={params}>
          {children}
        </Navbar>
        {children}
        <Footer lang={params.lang} />
      </body>
    </html>
  );
}
