import { Footer } from "@/app/components/landpage/Footer";
import Navbar from "@/app/components/landpage/Navbar";
import type { Metadata } from "next";
import { NextIntlClientProvider, useMessages } from "next-intl";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

type LocaleLayoutProps = {
  children: React.ReactNode;
  params: {
    locale: "en" | "de" | "ar";
  };
};

const RootLayout: React.FC<LocaleLayoutProps> = ({
    children,
        params:{ locale } }) => {
        const messages = useMessages();
        
        return (
            <html lang={locale}>
                <body className={inter.className}>
                    <NextIntlClientProvider messages={messages}>
                        <Navbar/>
                        {children}
                        <Footer />     
                    </NextIntlClientProvider>
                </body>
            </html>
        );
    }
export default RootLayout;